// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvNh7WwvC1KRu_Ca-NpL1XnGTY3FIY2pE',
    appId: '1:931245089327:web:b510b00bd85952cf765cda',
    messagingSenderId: '931245089327',
    projectId: 'ai-weather-bbdad',
    authDomain: 'ai-weather-bbdad.firebaseapp.com',
    storageBucket: 'ai-weather-bbdad.firebasestorage.app',
    measurementId: 'G-7R6KK5ZSVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfL8wFGYSOk7k-ZWC25DsHwq8d7w6xI3E',
    appId: '1:931245089327:android:02ede41a3f3ab093765cda',
    messagingSenderId: '931245089327',
    projectId: 'ai-weather-bbdad',
    storageBucket: 'ai-weather-bbdad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz8KlVSWWvQyPu11YNHFFDn9tsmdC4v-s',
    appId: '1:931245089327:ios:93fbafda977aa7dd765cda',
    messagingSenderId: '931245089327',
    projectId: 'ai-weather-bbdad',
    storageBucket: 'ai-weather-bbdad.firebasestorage.app',
    iosBundleId: 'com.example.aiWeather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz8KlVSWWvQyPu11YNHFFDn9tsmdC4v-s',
    appId: '1:931245089327:ios:93fbafda977aa7dd765cda',
    messagingSenderId: '931245089327',
    projectId: 'ai-weather-bbdad',
    storageBucket: 'ai-weather-bbdad.firebasestorage.app',
    iosBundleId: 'com.example.aiWeather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvNh7WwvC1KRu_Ca-NpL1XnGTY3FIY2pE',
    appId: '1:931245089327:web:83a2f32d2b6a0642765cda',
    messagingSenderId: '931245089327',
    projectId: 'ai-weather-bbdad',
    authDomain: 'ai-weather-bbdad.firebaseapp.com',
    storageBucket: 'ai-weather-bbdad.firebasestorage.app',
    measurementId: 'G-4J54LS9CQ1',
  );
}
